---
- name: Testing Custom db_status module
  hosts: abadan.masoudhhp.com

  tasks:
    - name: Check status of Oracle database
      db_status_old:
        state: check
        oracle_home: /u01/app/oracle/product/19.27.0/dbhome_1
        oracle_sid: cdb1
      become: true
      become_user: oracle
      register: db_status_result

    - name: Display database status
      ansible.builtin.debug:
        var: db_status_result
...
